NETWORK_SPEEDTEST_VERSION = 1.0
NETWORK_SPEEDTEST_SITE = $(BR2_EXTERNAL_APPLICATION_PATH)/package/network_speedtest/src
NETWORK_SPEEDTEST_SITE_METHOD = local

NETWORK_SPEEDTEST_DEPENDENCIES = dbus 

NETWORK_SPEEDTEST_CFLAGS = $(TARGET_CFLAGS)
NETWORK_SPEEDTEST_CFLAGS += -I$(STAGING_DIR)/usr/include/dbus-1.0
NETWORK_SPEEDTEST_CFLAGS += -I$(STAGING_DIR)/usr/lib/dbus-1.0/include

NETWORK_SPEEDTEST_LDFLAGS = $(TARGET_LDFLAGS)
NETWORK_SPEEDTEST_LDFLAGS += -L$(STAGING_DIR)/usr/lib -ldbus-1

define NETWORK_SPEEDTEST_BUILD_CMDS
	$(MAKE) CC="$(TARGET_CC)" -C $(@D) CFLAGS="$(NETWORK_SPEEDTEST_CFLAGS)" LDFLAGS="$(NETWORK_SPEEDTEST_LDFLAGS)"
endef

define NETWORK_SPEEDTEST_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/network_speedtest $(TARGET_DIR)/usr/bin
endef

define NETWORK_SPEEDTEST_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(BR2_EXTERNAL_APPLICATION_PATH)/package/network_speedtest/S99network_speedtest \
		$(TARGET_DIR)/etc/init.d/S99network_speedtest
endef

$(eval $(generic-package))