#!/bin/sh

case $1 in
    start)
	printf "Starting network_monitor: "
	start-stop-daemon --start --background -p /var/run/network_monitor.pid --exec /usr/bin/network_monitor
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping network_monitor: "
	start-stop-daemon -K -q -p /var/run/network_monitor.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
