#!/bin/sh

DAEMON=/usr/bin/network_monitor
PIDFILE=/var/run/network_monitor.pid

case "$1" in
    start)
        printf "Starting network_monitor: "
        start-stop-daemon --start --quiet --background --pidfile "$PIDFILE" --exec "$DAEMON"
        if [ $? -eq 0 ]; then
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;
    stop)
        printf "Stopping network_monitor: "
        start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
        if [ $? -eq 0 ]; then
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0